version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: docker build -t flask-app:0.01 Dockerfile
      - run: docker run -d -p 5000:5000 flask-app:0.01

workflows:
  build_now:
    jobs:
      - build